yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='main-view'),
    # Посты
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # создание записи
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=200)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Текст поста')
    pub_date = models.DateTimeField('Дата публикации',
                                    auto_now_add=True)
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        # выводим текст поста
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField('Текст комментария')
    pub_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments'
    )

    class Meta:
        ordering = ['-pub_date']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='unique_follow')
        ]

yatube/posts/forms.py
from django import forms
from django.urls import reverse_lazy

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': ('Текст поста:'),
            'group': ('Выберите группу'),
        }
    success_url = reverse_lazy('posts:profile')
    template_name = 'posts/create_post.html'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from posts.forms import CommentForm, PostForm
from .apps import get_paginator
from .models import Follow, Group, Post, User


def index(request):
    template = 'posts/index.html'
    page_obj = get_paginator(Post.objects.all(), request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    page_obj = get_paginator(group.posts.all(), request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author__username=username)
    count = post_list.count()
    page_obj = get_paginator(post_list, request)
    following = request.user.is_authenticated and author.following.filter(
        user=request.user).exists()
    context = {
        'page_obj': page_obj,
        'username': author,
        'count': count,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    count = post.author.posts.count()
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'count': count,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        form = form.save(commit=False)
        form.author = request.user
        form.save()
        return redirect('posts:profile', request.user.username)
    return render(request, 'posts/create_post.html', {'form': form, })


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    # информация о текущем пользователе доступна в переменной request.user
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = get_paginator(post_list, request)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}Новый пост{% endblock %}
{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        {% if is_edit %}
                            Редактировать запись
                        {% else %}
                            Добавить запись
                        {% endif %}
                    </div>
                    <div class="card-body">
                        {% if is_edit %}
                            <form method="post"
                                  enctype="multipart/form-data"
                                  action="{% url 'posts:post_edit' post.id %}">
                            {% else %}
                                <form method="post"
                                      enctype="multipart/form-data"
                                      action="{% url 'posts:post_create' %}">
                                {% endif %}
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary">
                                    {% if is_edit %}
                                        Сохранить
                                    {% else %}
                                        Добавить
                                    {% endif %}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}Подписки на автора{% endblock %}
{% block content %}
    <h1>Подписки на автора</h1>
    {% include 'includes/switcher.html' %}
    {% for post in page_obj %}
        {% include 'posts/includes/block_author.html' %}
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
        {{ post.text }}
    </p>
    {% include 'posts/includes/block_detail.html' %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Записи сообщества {{ group }}{% endblock %}
{% block header %}{{ group }}{% endblock %}
{% block content %}
    <p>
        {{ group.description }}
    </p>
    {% for post in page_obj %}
        {% include 'posts/includes/block_author.html' %}
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
        {{ post.text }}
    </p>
    {% include 'posts/includes/block_detail.html' %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
    {% cache 20 index_page page_obj.number%}
    <h1>Последние обновления на сайте</h1>
    {% include 'includes/switcher.html' %}
    {% for post in page_obj %}
        {% include 'posts/includes/block_author.html' %}
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
        {{ post.text }}
    </p>
    {% include 'posts/includes/block_detail.html' %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}Пост  {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
                {% if post.group %}
                    <li class="list-group-item">
                        Группа: {{ post.group }}
                        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                    </li>
                {% endif %}
                <li class="list-group-item">Автор: {{ post.author.get_full_name }}</li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Всего постов автора:  <span >{{ count }}</span>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
                </li>
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
            {{ post.text }}
            <br>
            <br>
            {% if user == post.author %}
                <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">редактировать запись</a>
            {% endif %}
        </p>
    </article>
    {% include 'posts/includes/comments.html' %} 
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ username.get_full_name }}{% endblock %}
{% block content %}
    <h1>Все посты пользователя {{ username.get_full_name }}</h1>
    <h3>Всего постов: {{ count }}</h3>
    <article>
        {% if following %}
            <a class="btn btn-lg btn-light"
               href="{% url 'posts:profile_unfollow' username.username %}"
               role="button">
                Отписаться
            </a>
        {% else %}
            <a class="btn btn-lg btn-primary"
               href="{% url 'posts:profile_follow' username.username %}"
               role="button">Подписаться</a>
        {% endif %}
        {% for post in page_obj %}
            {% include 'posts/includes/block_author.html' %}
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
            {{ post.text }}
        </p>
        {% include 'posts/includes/block_detail.html' %}
    {% endfor %}
</article>
{% include 'posts/includes/paginator.html' %}
{% endblock %}